# fichier de configuration de flexget
# recherche mes films souhaités de trakt.tv dans les sites de torrents et lance leur dl dans la seedbox
# le 1er janvier 2018

# priorités de recherche:
#  1. titre en fr
#  2. titre en en avec 'french'
#  3. titre en en

variables: secrets.yml

web_server: yes
# 2 fois par jour, a 9h et 20h
schedules:
  - tasks: [ lecture_trakt, movies-fr* ]
    schedule:
      hour: 9,20

templates:
  films:
    quality: 720p !h265 !hdrip !tc !ts !cam
    #seen: local
    content_size:
      min: 100
      max: 8000
    list_match:
      from:
        - movie_list: films
    list_remove:
      - trakt_list:
          account: '{? trakt.usr ?}'
          list: watchlist
    list_add:
      - trakt_list:
          account: '{? trakt.usr ?}'
          list: flexget found
    notify:
      entries:
        via:
          - slack:
              web_hook_url: '{? slack.hook_url ?}'
              username: flexget
              #icon_emoji: clapper
    # film est ajoute a la list seen
    # envoi vers rtorrent
    rtorrent:
      uri: '{? seedbox.uri ?}'
      username: '{? seedbox.usr ?}'
      password: '{? seedbox.pwd ?}'
      path: '{? seedbox.path ?}'
      custom1: films
    # ou envoi du .torrent dans un dossier local (repris par rtorrent)
    #download:
    #  path: '/storage/downloads/torrents/films/'
    #  filename: '{{title|pathscrub}}.torrent'

  recherche-multisite:
    discover:
      what:
        - movie_list: films
      from:
#        - piratebay:
#            category: movies
#            sort_by: seeds
        - rarbg:
            category: [48, 17, 44, 45]
            sorted_by: seeders
        - 1337x: yes
#    accept_all: yes # ca prend plusieurs fois le meme film
    # pour ne prendre que 1 fois chaque film je fais list_match
    
  films-fr:
    #titre francais
    tmdb_lookup:
      language: fr


  films-fr-en_title:
    #titre anglais avec 'french' dans le nom
    tmdb_lookup:
      language: en
    regexp:
      accept:
        - french
      reject:
        - vfq

  films-en:
    #titre anglais
    tmdb_lookup:
      language: en


tasks:

  lecture_trakt:
    priority: 1
    trakt_list:
      username: '{? trakt.usr ?}'
      account: '{? trakt.usr ?}'
      list: watchlist
      type: movies
    tmdb_lookup:
      language: fr
    accept_all: yes
    list_add:
      - movie_list: films

  movies-fr:
    priority: 10
    template:
      - films
      - films-fr
      - recherche-multisite


  movies-fr-en:
    priority: 20
    template:
      - films
      - films-fr-en_title
      - recherche-multisite


  movies-en:
    priority: 30
    template:
      - films
      - films-en
      - recherche-multisite

  movies-yts:
    rss: https://yts.am/rss/2017/all/all/6
    template:
      - films

  movies-yggtorrent:
    #si protec cloudflare
    #cfscraper: yes
    form:
      url: https://yggtorrent.com/user/login
      userfield: id
      passfield: pass
      username: '{? ygg.usr ?}'
      password: '{? ygg.pwd ?}'
    html:
      url: "https://yggtorrent.com/torrents/filmvideo/2183-film?per_page=20&order=desc&sort=publish_date"
      title_from: link
      links_re:
        - "/filmvidéo/.*[0-9]{5}-.*"
    urlrewrite:
      yggtorrent:
        regexp: 'https://yggtorrent.com/torrent/.*/.*/(?P<id>\d+)-(?P<name>.*)'
        format: 'http://yggtorrent.com/engine/download_torrent?id=\g<id>'
    regexp:
      reject:
        - vfq
    template:
      - films
      - films-fr
